# Generated by Django 6.0.1 on 2026-02-06 23:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("agricultural", "0001_initial"),
        ("general_master_config_master", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="crop",
            name="key_country",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="general_master_config_master.country",
            ),
        ),
        migrations.AddField(
            model_name="crop",
            name="key_department",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="general_master_config_master.department",
            ),
        ),
        migrations.AddField(
            model_name="crop",
            name="key_district",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="general_master_config_master.district",
            ),
        ),
        migrations.AddField(
            model_name="crop",
            name="key_province",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="general_master_config_master.province",
            ),
        ),
        migrations.AddField(
            model_name="crop",
            name="key_society",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="general_master_config_master.society",
            ),
        ),
    ]
