# Generated by Django 6.0.1 on 2026-02-06 23:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("agricultural", "0002_initial"),
        ("config", "0001_initial"),
        ("general_master_config_master", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="crop",
            name="key_user_created",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_created",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="crop",
            name="key_user_updated",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_updated",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="crop",
            name="status",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="config.status"
            ),
        ),
        migrations.AddField(
            model_name="farm",
            name="key_country",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="general_master_config_master.country",
            ),
        ),
        migrations.AddField(
            model_name="farm",
            name="key_department",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="general_master_config_master.department",
            ),
        ),
        migrations.AddField(
            model_name="farm",
            name="key_district",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="general_master_config_master.district",
            ),
        ),
        migrations.AddField(
            model_name="farm",
            name="key_province",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="general_master_config_master.province",
            ),
        ),
        migrations.AddField(
            model_name="farm",
            name="key_society",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="general_master_config_master.society",
            ),
        ),
        migrations.AddField(
            model_name="farm",
            name="key_user_created",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_created",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="farm",
            name="key_user_updated",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_updated",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="farm",
            name="status",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="config.status"
            ),
        ),
        migrations.AddField(
            model_name="field",
            name="key_farm",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="agricultural.farm"
            ),
        ),
        migrations.AddField(
            model_name="field",
            name="key_user_created",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_created",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="field",
            name="key_user_updated",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_updated",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="field",
            name="status",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="config.status"
            ),
        ),
        migrations.AddField(
            model_name="shift",
            name="key_user_created",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_created",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="shift",
            name="key_user_updated",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_updated",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="shift",
            name="status",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="config.status"
            ),
        ),
        migrations.AddField(
            model_name="stage",
            name="key_field",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="agricultural.field"
            ),
        ),
        migrations.AddField(
            model_name="stage",
            name="key_user_created",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_created",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="stage",
            name="key_user_updated",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_updated",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="stage",
            name="status",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="config.status"
            ),
        ),
        migrations.AddField(
            model_name="shift",
            name="key_stage",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="agricultural.stage"
            ),
        ),
    ]
