# Generated by Django 6.0.1 on 2026-03-05 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agricultural", "0003_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="crop",
            name="abbreviation",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name="crop",
            name="name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="farm",
            name="abbreviation",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name="farm",
            name="name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="field",
            name="abbreviation",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name="field",
            name="name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="shift",
            name="abbreviation",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name="shift",
            name="name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="stage",
            name="abbreviation",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name="stage",
            name="name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
