# Generated by Django 6.0.1 on 2026-02-21 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("general_master_config_master", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="country",
            name="iso_alpha_2",
            field=models.CharField(blank=True, max_length=2, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="country",
            name="iso_alpha_3",
            field=models.CharField(blank=True, max_length=3, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="country",
            name="phone_prefix",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
