# Generated by Django 6.0.1 on 2026-02-21 06:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("config", "0005_remove_status_restaurado"),
        (
            "general_master_config_master",
            "0003_country_iso_alpha_2_country_iso_alpha_3_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="country",
            name="iso_alpha_2",
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name="country",
            name="iso_alpha_3",
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AddConstraint(
            model_name="country",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("status_id", "bd7a3ed1-efdb-429b-9cb2-9999b7a12bab"), _negated=True
                ),
                fields=("iso_alpha_2",),
                name="unique_iso_alpha_2_not_annulled",
            ),
        ),
        migrations.AddConstraint(
            model_name="country",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("status_id", "bd7a3ed1-efdb-429b-9cb2-9999b7a12bab"), _negated=True
                ),
                fields=("iso_alpha_3",),
                name="unique_iso_alpha_3_not_annulled",
            ),
        ),
    ]
