# Generated by Django 6.0.1 on 2026-02-21 08:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("config", "0005_remove_status_restaurado"),
        (
            "general_master_config_master",
            "0004_alter_country_iso_alpha_2_alter_country_iso_alpha_3_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="country",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("status_id", "bd7a3ed1-efdb-429b-9cb2-9999b7a12bab"), _negated=True
                ),
                fields=("code",),
                name="unique_country_code_not_annulled",
            ),
        ),
        migrations.AddConstraint(
            model_name="country",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("status_id", "bd7a3ed1-efdb-429b-9cb2-9999b7a12bab"), _negated=True
                ),
                fields=("name",),
                name="unique_country_name_not_annulled",
            ),
        ),
        migrations.AddConstraint(
            model_name="department",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("status_id", "bd7a3ed1-efdb-429b-9cb2-9999b7a12bab"), _negated=True
                ),
                fields=("code", "key_country"),
                name="unique_department_code_per_country_not_annulled",
            ),
        ),
        migrations.AddConstraint(
            model_name="department",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("status_id", "bd7a3ed1-efdb-429b-9cb2-9999b7a12bab"), _negated=True
                ),
                fields=("name", "key_country"),
                name="unique_department_name_per_country_not_annulled",
            ),
        ),
    ]
