# Generated by Django 6.0.1 on 2026-02-21 08:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("config", "0005_remove_status_restaurado"),
        (
            "general_master_config_master",
            "0005_country_unique_country_code_not_annulled_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="country",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("status_id", "bd7a3ed1-efdb-429b-9cb2-9999b7a12bab"), _negated=True
                ),
                fields=("abbreviation",),
                name="unique_country_abbreviation_not_annulled",
            ),
        ),
    ]
