# Generated by Django 6.0.1 on 2026-02-26 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "general_master_config_master",
            "0006_country_unique_country_abbreviation_not_annulled",
        ),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="country",
            name="unique_country_abbreviation_not_annulled",
        ),
    ]
