# Generated by Django 6.0.1 on 2026-02-07 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("config", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="status",
            name="color_code",
            field=models.CharField(
                default="#6C757D",
                help_text="Hex color code (e.g., #28A745)",
                max_length=7,
            ),
        ),
    ]
