# Generated by Django 6.0.1 on 2026-02-07 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("config", "0002_status_color_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="status",
            name="icon",
            field=models.CharField(
                blank=True,
                help_text="Icon name (e.g., fas fa-check)",
                max_length=50,
                null=True,
            ),
        ),
    ]
