# Generated by Django 6.0.1 on 2026-03-05 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("config", "0005_remove_status_restaurado"),
    ]

    operations = [
        migrations.AlterField(
            model_name="status",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="status",
            name="name",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="typestatus",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="typestatus",
            name="name",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
