# Generated by Django 6.0.1 on 2026-02-06 23:07

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("key_event", models.UUIDField(db_index=True)),
                ("name_module", models.CharField(db_index=True, max_length=50)),
                ("name_table", models.CharField(db_index=True, max_length=50)),
                ("record_id", models.CharField(db_index=True, max_length=64)),
                ("key_user", models.UUIDField(db_index=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                "db_table": "audit_log",
            },
        ),
        migrations.CreateModel(
            name="AuditLogDetail",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("column_name", models.CharField(db_index=True, max_length=50)),
                ("old_value", models.TextField(blank=True, null=True)),
                ("new_value", models.TextField(blank=True, null=True)),
                (
                    "key_audit_log",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="details",
                        to="audit.auditlog",
                    ),
                ),
            ],
            options={
                "db_table": "audit_log_detail",
            },
        ),
    ]
