# Generated by Django 6.0.1 on 2026-02-10 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("meteorite_auth", "0002_verificationcode"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="dni",
            field=models.CharField(blank=True, max_length=8, null=True, unique=True),
        ),
    ]
