# Generated by Django 6.0.1 on 2026-03-05 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("access", "0004_seed_audit_events"),
    ]

    operations = [
        migrations.AddField(
            model_name="permission",
            name="method",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name="action",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="action",
            name="name",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="event",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="event",
            name="name",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="group",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="group",
            name="name",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="menu",
            name="subject",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="permission",
            name="api_url",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="permission",
            name="decorator_name",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="permission",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="permission",
            name="name",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="role",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="role",
            name="name",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="system",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="system",
            name="name",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
