# Generated by Django 6.0.1 on 2026-03-05 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("access", "0005_permission_method_alter_action_description_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="permissionrole",
            unique_together={("permission", "role")},
        ),
        migrations.AlterUniqueTogether(
            name="permissionsystem",
            unique_together={("permission", "system")},
        ),
        migrations.AlterUniqueTogether(
            name="usergroup",
            unique_together={("user_id", "group")},
        ),
        migrations.AlterUniqueTogether(
            name="usergrouprole",
            unique_together={("user_id", "group", "role")},
        ),
        migrations.AlterUniqueTogether(
            name="userrole",
            unique_together={("user_id", "role")},
        ),
    ]
